# Site settings
title: BeagleBone Black Inverted Pendulum
email: troy@dack.com.au
description: >
  This repository contains the code for my 4th year Design project.
  A BeagleBone Black is used to control an inverted pendulum system.
baseurl: "/inverted-pendulum" # the subpath of your site, e.g. /blog/
url: "http://github.dack.com.au" # the base hostname & protocol for your site
twitter_username: tdack
github_username:  tdack

# Build settings
markdown: kramdown
