#!/bin/bash


case $1 in
  bbb)
	sudo ip route add default gw 192.168.7.1
	if grep -Fq nameserver /etc/resolv.conf
	then
		echo "nameserver entry found"
		;;
	else
		echo "no nameserver entry found"
#		echo "namserver 8.8.8.8" >> /etc/resolv.conf
	fi
	;;
  vm)
	sudo ip addr add 192.168.7.1 eth1
	sudo ip route add 192.168.7.0/24 dev eth1
	sudo iptables -A POSTROUTING -t nat -j MASQUERADE
	echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward > /dev/null
	;;
esac

